package org.openmrs.module.htmlformentry.schema;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.openmrs.Concept;
import org.openmrs.Field;
import org.openmrs.FieldType;
import org.openmrs.Form;
import org.openmrs.FormField;
import org.openmrs.api.FormService;
import org.openmrs.api.context.Context;
import org.openmrs.module.htmlformentry.FormEntrySession;
import org.openmrs.module.htmlformentry.HtmlForm;
import org.openmrs.module.htmlformentry.HtmlFormEntryUtil;


/**
 * This class is responsible for updating the core OpenMRS Form Schema,
 * when saving an HTML Form
 * @author jportela
 *
 */
public class FormSchemaUpdater {
	
	
	private HtmlForm htmlForm;
	private FormField obsSection = null;
	private FormField patientSection = null;
	private FormField encounterSection = null;
	private Form form = null;
	private HashMap<Integer, LinkedList<FormField>> formSchemaFields = null;
	private HashMap<String, FormField> formSchemaSections = null;
	private FormService formService = null;
	private FieldType sectionType = null;
	private FieldType conceptType = null;
	private FieldType setOfConceptsType = null;
	
    protected final Log log = LogFactory.getLog(getClass());
	
	public FormSchemaUpdater(HtmlForm htmlForm) {
		this.htmlForm = htmlForm;
		form = htmlForm.getForm();
		formService = Context.getFormService();		
	}
	
	/** Updates the Core OpenMRS Schema
	 * To be called on HtmlFormEntryServiceImpl.saveHtmlForm
	 */
	public void updateSchema() {
		
		//Retrieves the FormEntrySession
		FormEntrySession session = null;
		try {
			session = new FormEntrySession(HtmlFormEntryUtil.getFakePerson(), htmlForm);
		} catch (Exception e) {	//TODO: Better exception handling
			e.printStackTrace();
		}
		
		sortFormFieldsByParentId(form.getFormFields());

        HtmlFormSchema schema = session.getContext().getSchema();	//contains the html form schema
        List <HtmlFormSection> sections = schema.getSections();		//gets a list with all sections of the Html Form
        
		findOrCreateDefaultFieldTypes();
        findOrCreateDefaultSections();
        
        //iterates through the sections
        //the first section stores all sections... weird...
        handleSections(sections.get(0).getSections(), null);
        handleFields(sections.get(0).getFields(), obsSection);
	}
	
	/**
	 * Retrieves the Default sections from the Data Model
	 * If they cannot be found, it will automatically create
	 * new sections on the Data Model
	 */
	private void findOrCreateDefaultSections()
	{
		if (!findDefaultSections())
			createDefaultSections();
	}
	
	/**
	 * Retrieves the OBS, PATIENT and ENCOUNTER sections from the
	 * Data Model
	 * @return true if all sections were found
	 * 
	 */
	private boolean findDefaultSections() {
		
		obsSection = formSchemaSections.get("OBS");
		patientSection = formSchemaSections.get("PATIENT");
		encounterSection = formSchemaSections.get("ENCOUNTER");
			
		if (!(obsSection == null || patientSection == null || encounterSection == null))
			return true;
		else
			return false;
	}

	
	/**
	 * Populates the "Section" and "Concept" field type from the DB. If it doesn't exist
	 * it will be created.
	 */
	
	private void findOrCreateDefaultFieldTypes() {
		List<FieldType> types = formService.getAllFieldTypes();
		
		//retrieves the Section field type
		for (FieldType type : types) {
			if (type.getName().equals("Section")) {
				sectionType = type;
			}
			else if (type.getName().equals("Concept")) {
				conceptType = type;
			}
			else if (type.getName().equals("Set of Concepts")) {
				setOfConceptsType = type;
			}
			if (!(sectionType == null || conceptType == null || setOfConceptsType == null))
				break;
		}
		
		//if it could not be found, create a new one
		if (sectionType == null) {
			sectionType = createFieldType("Section", true);
		}
		if (conceptType == null) {
			conceptType = createFieldType("Concept", false);
		}
		if (setOfConceptsType == null) {
			setOfConceptsType = createFieldType("Set of Concepts", true);
		}
				
	}
	
	private FieldType createFieldType(String name, boolean isSet) {
		
		FieldType fieldType = new FieldType();
		fieldType.setName(name);
		fieldType.setDescription("Generated by HtmlFormEntry module");
		fieldType.setIsSet(isSet);
		return formService.saveFieldType(fieldType);				
	}


	private FormField createDefaultSection(String name) {
		
		Field sectionField = null;
		
		List<Field> fields = formService.getAllFields();
		
		for (Field field : fields) {
			if (field.getName().equals(name)) {
				sectionField = field;
				break;
			}
		}
		
		if (sectionField == null) {
			sectionField = new Field();
			sectionField.setName(name);
			sectionField.setDescription("Generated by HtmlFormEntry module");
			sectionField.setFieldType(sectionType);
		}
		
		FormField formField = new FormField();
		formField.setField(sectionField);
		formField.setForm(form);
		formField.setName(name);
		formField.setDescription("Generated by HtmlFormEntry module");
		return formService.saveFormField(formField);
				
	}
	
	/**
	 * Creates the Default Sections in the Data Model (OBS,
	 * PATIENT, ENCOUNTER), if they were not found
	 */
	private void createDefaultSections() { 
		 		
		if (obsSection == null) {
			obsSection = createDefaultSection("OBS");
		}
		if (patientSection == null) {
			patientSection = createDefaultSection("PATIENT");
		}
		if (encounterSection == null) {
			encounterSection = createDefaultSection("ENCOUNTER");
		}
		
	}
	
	public void handleSections(List<HtmlFormSection> sections, FormField parent) {
		for (int i = 0; i < sections.size(); i++) {
        	
			HtmlFormSection section = sections.get(i);
        	//this should add the sections to their place in the form schema
        	//keep in mind that <obs> tags should go into an OBS section, 
        	//and all the other "special" sections (PATIENT, ENCOUNTER)
        	
        	handleSection(section, parent, i);
        }
	}
	
private FormField findFormField(Integer conceptId, Integer parentId) {
		
		LinkedList<FormField> fields = formSchemaFields.get(parentId);
		
		if (fields == null) return null;
		
		for (FormField field : fields) {
			if (field.getField().getConcept().getConceptId().equals(conceptId)) {
				fields.remove(field);		//removes the field, already found
				return field;
			}
		}
		
		return null;
	}

	private FormField findFormSection(String name) {
		
		return formSchemaSections.get(name);
	}
	
	private Field createSection(String name) {
		Field field = new Field();
		field.setName(name);
		field.setDescription("Generated by Html Form Entry Module");
		field.setFieldType(sectionType); 
		return field;
	}
	
	private Field findOrCreateField(Concept concept, FieldType type) {
		
		List<Field> fields = formService.getFieldsByConcept(concept);
		
		if (fields.isEmpty()) {
			Field field = new Field();
			field.setConcept(concept);
			field.setName("" + concept.getName());
			field.setDescription("Generated by Html Form Entry Module");
			field.setFieldType(type); 
			return field;
		}
		else
			return fields.get(0);
	}
	
	private FormField createFormField(Concept concept, String name, FieldType type, FormField parent, int index) {

		Field field = findOrCreateField(concept, type);
		
		FormField formField = new FormField();
		formField.setForm(form);
		formField.setField(field);
		formField.setParent(parent);
		formField.setSortWeight((float)index);
		formField.setName("" + name);
		formField.setDescription("Generated by Html Form Entry Module");
		return formService.saveFormField(formField);
	}
	
	private FormField createFormSection(String name, FormField parent, int index) {

		Field field = createSection(name);
		
		FormField formField = new FormField();
		formField.setForm(form);
		formField.setField(field);
		formField.setParent(parent);
		formField.setSortWeight((float)index);
		formField.setName("" + name);
		formField.setDescription("Generated by Html Form Entry Module");
		return formService.saveFormField(formField);
	}

	private FormField findOrCreateFormSection(String name, FormField parent, int index) {
		
		FormField field = findFormSection(name);
		
		if (field == null)
			field = createFormSection(name, parent, index);
		
		return field;
	}
	

	private FormField findOrCreateFormField(Concept concept, FieldType type, FormField parent, int index) {
		FormField field = null;
		
		if (concept != null && parent != null)
			field = findFormField(concept.getConceptId(), parent.getId());
		
		if (field == null)
			field = createFormField(concept, "" + concept.getName(), type, parent, index);
		
		return field; 
	}
	
	public void handleSection(HtmlFormSection section, FormField parent, int index) {
		List<HtmlFormField> fields = section.getFields();
		List<HtmlFormSection> sections = section.getSections();
		
		log.info("HtmlFormSection " + section.getName() + " | " + fields.size() + " fields | " + sections.size() + " sections.");
		
		parent = (parent == null) ? obsSection : parent;
		
		FormField formField = findOrCreateFormSection("" + section.getName(), parent, index);	

		handleFields(fields, formField);
		
		if (!sections.isEmpty())
			handleSections(sections, formField);
	}
	
	public void handleFields(List<HtmlFormField> fields, FormField parent) {
		for (int i = 0; i < fields.size(); i++) {
			HtmlFormField field = fields.get(i);
			handleField(field, parent, i);
		}
	}
	
	//TODO: Labels for the names?
	public void handleField(HtmlFormField htmlFormField, FormField parent, int index) {
		if (htmlFormField instanceof ObsField) {
    		ObsField obsField = (ObsField) htmlFormField;
    		log.info("ObsField - " + obsField.getQuestion().getName() + " - ConceptID: " + obsField.getQuestion().getId());
    		
    		findOrCreateFormField(obsField.getQuestion(), conceptType, parent, index);

		}

		else if (htmlFormField instanceof ObsGroup) {
    		ObsGroup obsGroup = (ObsGroup) htmlFormField;
    		
    		log.info("ObsField - " + obsGroup.getConcept().getName() + " - ConceptID: " + obsGroup.getConcept().getId());
    		
    		FormField formField = findOrCreateFormField(obsGroup.getConcept(), setOfConceptsType, parent, index);
    		
    		List<HtmlFormField> fields = obsGroup.getChildren();
    		
    		for (int i = 0; i < fields.size(); i++) {
    			HtmlFormField groupField = fields.get(i);
    			handleField(groupField, formField, i);
    		}
			
		}
	}
	
	private void sortFormFieldsByParentId(Set<FormField> formFields) {
		formSchemaFields = new HashMap<Integer, LinkedList<FormField>>();
		formSchemaSections = new HashMap<String, FormField>();
		
		for (FormField field : formFields) {
			
			if (field.getParent() == null) //top level elements: OBS, PATIENT, ENCOUNTER
			{
				String name = field.getField().getName();
				formSchemaSections.put("" + name, field);
			}
			else if (field.getField().getConcept() == null) {	//Section...
				String name = field.getField().getName();
				formSchemaSections.put("" + name, field);
			}
			else {
				Integer parentId = field.getParent().getId();	

				LinkedList<FormField> fields = null;
				
				if (formSchemaFields.containsKey(parentId)) {
					fields = formSchemaFields.get(parentId);
				}
				else {
					fields = new LinkedList<FormField>();
					formSchemaFields.put(parentId, fields);
				}
				fields.add(field);
			}
		}
	}
	
	

}
